kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: test
    image: rust:1.50
    commands:
      - cargo build --verbose --all
      - cargo test --verbose --all
  - name: build
    image: plugins/docker
    settings:

